#!/usr/bin/env bash
set -euo pipefail

# colors
GREEN='\033[0;32m'
NC='\033[0m'

log() {
    echo -e "${GREEN}==>${NC} $1"
}

# clone or update repo
REPO_PATH="$HOME/.config/nixpkgs"
if [[ ! -d "$REPO_PATH" ]]; then
    log "cloning box..."
    git clone https://github.com/realbikmaev/box.git/ "$REPO_PATH"
else
    log "updating box..."
    cd "$REPO_PATH"
    git pull
fi

cd "$REPO_PATH"
./install.sh
